# Generated by Django 5.2.3 on 2025-06-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_event_id_remove_eventimage_image_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date'], 'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
        migrations.AlterModelOptions(
            name='eventimage',
            options={'verbose_name': 'eventImage', 'verbose_name_plural': 'eventImages'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'item', 'verbose_name_plural': 'items'},
        ),
        migrations.RenameField(
            model_name='eventimage',
            old_name='image_url',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('concert', 'Concert'), ('sports', 'Sports'), ('theater', 'Theater'), ('presentation', 'Presentation'), ('conference', 'Conference'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('confirmed', 'Confirmed'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterModelTable(
            name='event',
            table=None,
        ),
        migrations.AlterModelTable(
            name='eventimage',
            table=None,
        ),
        migrations.AlterModelTable(
            name='order',
            table=None,
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table=None,
        ),
    ]
